forkliftOperatorAnsible:
  forkliftOperator:
    repo: gmehta3
    tag: main-head
    args:
    - --health-probe-bind-address=:6789
    - --metrics-bind-address=127.0.0.1:8080
    - --leader-elect
    - --leader-election-id=forklift-operator
    env:
      tag: main-head
      repo: gmehta3
      ansibleGathering: explicit
      apiImage: forklift-api
      blockOverhead: ""
      cdiExportTokenTtl: ""
      cleanupRetries: ""
      controllerImage: forklift-controller
      filesystemOverhead: ""
      mustGatherImage: forklift-must-gather
      openstackPopulatorImage: openstack-populator
      ovaProviderServerImage: ova-provider-server
      ovirtOsMap: ""
      ovirtPopulatorImage: ovirt-populator
      populatorControllerImage: populator-controller
      snapshotRemovalTimeout: ""
      snapshotStatusCheckRate: ""
      uiPluginImage: forklift-console-plugin
      validationImage: validation
      virtCustomizeMap: ""
      virtV2VDontRequestKvm: ""
      virtV2VImage: virt-v2v
      vsphereOsMap: ""
      vsphereXcopyVolumePopulatorImage: ""
    image:
      repository: gmehta3/forklift-operator
      tag: main-head
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
kubernetesClusterDomain: cluster.local
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ""
